### PR TITLE
Condaification

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
@gregvonkuster what do you think about adding a bioblend test to travis that actually runs an imaging tool?

**Comment by gregvonkuster** [comment]
@bgruening sure!  I'll need some instructions for doing this, can you provide some direction?

**Comment by bgruening** [comment]
@gregvonkuster please look at the script section: https://github.com/bgruening/docker-galaxy-imaging/blob/master/.travis.yml#L63

I guess if you have a small bioblend script that uploads a datasets and runs a tools or even a workflow on it you can execute this script in this section. You could to this as well for the Chip-Exo Flavour.

**Comment by gregvonkuster** [comment]
@bgruening Thanks for the info - is there a working example of this that I can take a look at?

**Pull request merged**
